os:
    - osx
    - linux
dist: trusty
language: cpp
addons:
    apt:
        packages:
            - qt5-default
            - libqt5x11extras5-dev
            - qttools5-dev-tools

env:
    - BUILDTYPE=Release
    - BUILDTYPE=Debug

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi

script:
    - mkdir build/
    - cd build/
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILDTYPE
    - make

compiler:
    - gcc
    - clang
