name: Ubuntu
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  targetName: danmaQ
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        qt_ver: [6.8.2]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_ver }}
          modules: 'qtwebengine'
          cache: true
      - name: Install other dependencies
        run: sudo apt-get install -y cmake ninja-build flatpak flatpak-builder
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build flatpak
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub org.kde.Sdk//5.15 io.qt.qtwebengine.BaseApp//5.15 -y
          sudo flatpak-builder --repo=repo --force-clean build-dir org.tuna.danmaQ.local.json
          sudo flatpak build-bundle repo danmaQ.flatpak org.tuna.danmaQ
        working-directory: flatpak
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.targetName }}.linux.amd64.flatpak
          path: flatpak/danmaQ.flatpak
      - name: Update to release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: flatpak/danmaQ.flatpak
          asset_name: ${{ env.targetName }}.linux.amd64.flatpak
          tag: ${{ github.ref }}
          overwrite: true
